### ISSUE TITLE
Add screenshots to Readme

### ISSUE THREAD

**Issue by JRavi2** [JRavi2/Chat-Analyzer#4]
Use the test exports to add screenshots of graphs and text outputs.

**Comment by asaraf7** [comment]
I have collected some screenshots. Broadly 3 kinds of graphs are possible I think.

**Comment by JRavi2** [comment]
@asaraf7 That's great! Just open up a PR, and we'll move ahead from there :)
If you need any help creating a PR, here's a nice guide: https://opensource.guide/how-to-contribute/#opening-a-pull-request

**Comment by asaraf7** [comment]
Should I send a PR directly to this repo or should I fork it first and then send it to the forked one?

**Comment by JRavi2** [comment]
Here are the basic steps:
1. Fork this repo 
2. Clone the forked repo
3. Create a new branch (`git checkout -b name-of-the-branch`)
4. Make the necessary changes
5. Stage the changes (`git add .`) and commit them (`git commit -m "Commit Message"`)
4. Push the changes to the forked repo (using `git push -u origin name-of-the-branch-from-step-3`)
5. Make a PR from the forked repo to this repo

I'll soon get a proper contributing guide going. Till then, try these steps out, and if you get stuck on any step, feel free to ask here or on the telegram group.

**Comment by asaraf7** [comment]
I've done it. I know it isn't good. Will try to improve!
